# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc4db88254347db6b2276d1e73f68b916a23e995e8837c215ee255f7fcc293dba74d86613ff887192f5740de7cd4b8fa01107852436c0d2670845dd20b3f6620

test:
  secret_key_base: 865a9d57ece93c507b7401d5c39d2198914ba1a2511340fb04cdf3a00eccb48a3fb92dfdae4bba85d2b8422d43200119300f3a97703f833489c4b343dbefdfe6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
